### ISSUE TITLE
java.lang.NullPointerException: Profile name must not be null

### ISSUE THREAD

**Issue by Nanpure** [Archy-X/AuraSkills#240]
### Server software and version

Paper 1.20.2

### Expected behavior

Show the skill ranking

### Actual behavior

Nothing (in game) and error in the log

### How to reproduce

/skills -> alchemy -> your skill ranking

I'm assuming that there is a problem somewhere with my data. I don't know how to troubleshoot this further, as I don't know what the problem is.

### Additional information

```
[18:24:34 ERROR]: Error while opening SmartInventory:
java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248) ~[paper-1.20.2.jar:git-Paper-318]
        at com.archyx.aureliumskills.menus.leaderboard.LeaderboardPlayerItem.onItemModify(LeaderboardPlayerItem.java:80) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.menus.leaderboard.LeaderboardPlayerItem.onItemModify(LeaderboardPlayerItem.java:22) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.slate.menu.MenuInventory.modifyBaseItem(MenuInventory.java:437) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.slate.menu.MenuInventory.addTemplateItem(MenuInventory.java:263) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.slate.menu.MenuInventory.init(MenuInventory.java:155) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.inv.SmartInventory.open(SmartInventory.java:89) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.inv.SmartInventory.open(SmartInventory.java:59) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.slate.menu.MenuManager.openMenu(MenuManager.java:278) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.slate.menu.MenuManager.openMenu(MenuManager.java:282) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.menus.levelprogression.RankItem.onClick(RankItem.java:60) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.slate.menu.MenuInventory.lambda$addSingleItemToInventory$0(MenuInventory.java:355) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.inv.ClickableItem.run(ClickableItem.java:135) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.archyx.aureliumskills.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:202) ~[AureliumSkills-Beta1.3.24.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at com.archyx.aureliumskills.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:202) ~[AureliumSkills-Beta1.3.24.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3108) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by C4BR3R4** [comment]
The same thing happens to me.
