### ISSUE TITLE
java.util.ConcurrentModificationException from unknown source

### ISSUE THREAD

**Issue by Nanpure** [Archy-X/AuraSkills#252]
### Server software and version

Paper 1.20.4

### Expected behavior

n/a

### Actual behavior

n/a

### How to reproduce

Unknown.

### Additional information

Spotted this in the log today. I don't know what caused it or how to reproduce it.

```2024-03-30 17:02:58 [auraskills-async-task-31/WARN] java.util.ConcurrentModificationException
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1792)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at net.minecraft.world.entity.ai.attributes.AttributeMapBase.b(AttributeMapBase.java:45)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.updateScaledHealth(CraftPlayer.java:2739)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.updateScaledHealth(CraftPlayer.java:2734)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.setHealthScaled(CraftPlayer.java:2710)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.bukkit.trait.HpTrait.applyScaling(HpTrait.java:162)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.bukkit.trait.HpTrait.setHealth(HpTrait.java:152)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.bukkit.trait.HpTrait.reload(HpTrait.java:68)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.bukkit.trait.TraitImpl.onReload(TraitImpl.java:27)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.bukkit.stat.BukkitStatManager.reloadStat(BukkitStatManager.java:54)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.common.stat.StatManager.reloadStats(StatManager.java:86)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.common.stat.StatManager.updateStats(StatManager.java:81)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.common.storage.StorageProvider.load(StorageProvider.java:30)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at AuraSkills-2.0.4.jar//dev.aurelium.auraskills.bukkit.listeners.PlayerJoinQuit.lambda$loadUserAsync$2(PlayerJoinQuit.java:68)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-03-30 17:02:58 [auraskills-async-task-31/WARN]     at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
This is probably a Paper issue because the only thing my code is doing is calling Player#setHealthScaled(true).
