### ISSUE TITLE
Error opeing Slate Menu skill

### ISSUE THREAD

**Issue by vubaolinh123** [Archy-X/AuraSkills#295]
### Server software and version

Paper 1.19.4

### Expected behavior

I type the command /skill and /skills or /auraskills:skill to open the Skill Menu

### Actual behavior

No Menu appears and only in the console does this warning appear
![image](https://github.com/Archy-X/AuraSkills/assets/73287503/954cb5f5-e3af-4481-ad72-7e5f33dca46d)

### How to reproduce

Run the plugin with version 2.1.2 with Paper 1.19.4 then go into the game and type /skill

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
Run the command /skills reload and check the console for errors. This is likely a YAML syntax error with your modifications to the menu/skills.yml file. You can use an online YAML validator to check where the syntax error is.

**Comment by vubaolinh123** [comment]
This is the log after running /skills reload
`
[11:26:52 INFO]: [AuraSkills] Loaded 21 message files
[11:26:52 WARN]: java.lang.reflect.InvocationTargetException
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:26:52 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:26:52 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.createHook(HookRegistrar.java:62)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.registerHooks(HookRegistrar.java:38)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.config.BukkitConfigProvider.loadOptions(BukkitConfigProvider.java:78)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.commands.ReloadExecutor.reload(ReloadExecutor.java:31)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.commands.SkillsRootCommand.reload(SkillsRootCommand.java:63)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:26:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BaseCommand.execute(BaseCommand.java:513)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.RootCommand.execute(RootCommand.java:99)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[11:26:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:26:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:908)
[11:26:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:871)
[11:26:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:504)
[11:26:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:451)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1411)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1182)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11:26:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[11:26:52 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class dev.aurelium.auraskills.bukkit.util.VersionUtils
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook.registerListeners(ProtocolLibHook.java:68)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook.<init>(ProtocolLibHook.java:34)
[11:26:52 WARN]:        ... 28 more
[11:26:52 WARN]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NumberFormatException: For input string: "19.4-R0" [in thread "Server thread"]
[11:26:52 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[11:26:52 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:668)
[11:26:52 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:786)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.VersionUtils.getMajorVersion(VersionUtils.java:52)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.VersionUtils.<clinit>(VersionUtils.java:9)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook.registerListeners(ProtocolLibHook.java:68)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook.<init>(ProtocolLibHook.java:34)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:26:52 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:26:52 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.createHook(HookRegistrar.java:62)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.registerHooks(HookRegistrar.java:38)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.config.BukkitConfigProvider.loadOptions(BukkitConfigProvider.java:78)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.AuraSkills.onEnable(AuraSkills.java:209)
[11:26:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[11:26:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[11:26:52 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11:26:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11:26:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:557)
[11:26:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:468)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:642)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[11:26:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1110)
[11:26:52 WARN]:        ... 2 more
[11:26:52 WARN]: [AuraSkills] Failed to register hook ProtocolLib: Failed to construct hook using reflection: null
[11:26:52 WARN]: dev.aurelium.auraskills.common.hooks.HookRegistrationException: Failed to construct hook using reflection: null
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.createHook(HookRegistrar.java:65)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.registerHooks(HookRegistrar.java:38)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.config.BukkitConfigProvider.loadOptions(BukkitConfigProvider.java:78)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.commands.ReloadExecutor.reload(ReloadExecutor.java:31)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.commands.SkillsRootCommand.reload(SkillsRootCommand.java:63)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:26:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:26:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BaseCommand.execute(BaseCommand.java:513)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.RootCommand.execute(RootCommand.java:99)
[11:26:52 WARN]:        at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[11:26:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:26:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:908)
[11:26:52 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:871)
[11:26:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:504)
[11:26:52 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:451)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1411)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1182)
[11:26:52 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11:26:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[11:26:52 INFO]: [AuraSkills] Loaded 114 config options in 5 ms
[11:26:52 INFO]: [AuraSkills] Loaded 3 blocked worlds.
[11:26:52 INFO]: I'm sorry, but there was an error performing this command.
[11:26:52 ERROR]: [AuraSkills] [ACF] Exception in command: skills reload 
[11:26:52 ERROR]: [AuraSkills] [ACF] java.lang.NoClassDefFoundError: Could not initialize class dev.aurelium.auraskills.bukkit.util.VersionUtils
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.item.BukkitPotionType.applyToMeta(BukkitPotionType.java:67)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.ConfigurateItemParser.parsePotionData(ConfigurateItemParser.java:242)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.ConfigurateItemParser.parseItemMeta(ConfigurateItemParser.java:116)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.ConfigurateItemParser.parseBaseItem(ConfigurateItemParser.java:98)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.ConfigurateItemParser.parseItem(ConfigurateItemParser.java:56)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.ConfigurateItemParser.parseItem(ConfigurateItemParser.java:52)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.item.BukkitSourceMenuItems.parseAndRegisterMenuItem(BukkitSourceMenuItems.java:27)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.common.source.SourceLoader.registerMenuItem(SourceLoader.java:233)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.common.source.SourceLoader.loadSources(SourceLoader.java:109)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.common.skill.SkillLoader.loadSources(SkillLoader.java:160)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.common.skill.SkillLoader.loadSkill(SkillLoader.java:100)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.common.skill.SkillLoader.loadSkills(SkillLoader.java:76)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.AuraSkills.loadSkills(AuraSkills.java:343)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.commands.ReloadExecutor.reload(ReloadExecutor.java:36)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.commands.SkillsRootCommand.reload(SkillsRootCommand.java:63)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BaseCommand.execute(BaseCommand.java:513)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.RootCommand.execute(RootCommand.java:99)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:908)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:871)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.dedicated.DedicatedServer.bh(DedicatedServer.java:504)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:451)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1411)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1182)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.Thread.run(Thread.java:840)
[11:26:52 ERROR]: [AuraSkills] [ACF] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NumberFormatException: For input string: "19.4-R0" [in thread "Server thread"]
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.Integer.parseInt(Integer.java:668)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.Integer.parseInt(Integer.java:786)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.VersionUtils.getMajorVersion(VersionUtils.java:52)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.util.VersionUtils.<clinit>(VersionUtils.java:9)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook.registerListeners(ProtocolLibHook.java:68)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook.<init>(ProtocolLibHook.java:34)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.createHook(HookRegistrar.java:62)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.hooks.HookRegistrar.registerHooks(HookRegistrar.java:38)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.config.BukkitConfigProvider.loadOptions(BukkitConfigProvider.java:78)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at AuraSkills-2.1.2.jar//dev.aurelium.auraskills.bukkit.AuraSkills.onEnable(AuraSkills.java:209)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:557)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:468)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:642)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311)
[11:26:52 ERROR]: [AuraSkills] [ACF]    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1110)
[11:26:52 ERROR]: [AuraSkills] [ACF]    ... 2 more
`

**Comment by vubaolinh123** [comment]
> menu/skills.yml

As for menu/skills.yml, I haven't modified anything, they are all automatically generated. And here is the log after I ran the reload command
https://jumpshare.com/s/J9xpJnWdRaz4SxHSP2VK

**Comment by vubaolinh123** [comment]
> Run the command /skills reload and check the console for errors. This is likely a YAML syntax error with your modifications to the menu/skills.yml file. You can use an online YAML validator to check where the syntax error is.

![image](https://github.com/Archy-X/AuraSkills/assets/73287503/1b0ee7eb-8cba-48b3-a91a-77e2a9c95afa)
I used VSCODE to check syntax errors but didn't see any errors

**Comment by Archy-X** [comment]
Are you sure you are using an official Paper build? I just tested with Paper 1.19.4 and did not this error. It would probably also be fixed if you updated to 1.20.4/6.

**Comment by vubaolinh123** [comment]
> Are you sure you are using an official Paper build? I just tested with Paper 1.19.4 and did not this error. It would probably also be fixed if you updated to 1.20.4/6.

It seems I downloaded a version of paper with some customizations and that caused the plugin to not work properly. After downloading the original version from the home page again, the plugin worked as expected, thanks for your help.
