### ISSUE TITLE
error on skill top command

### ISSUE THREAD

**Issue by xcoolerboy** [Archy-X/AuraSkills#323]
### Server software and version

1.21.1

### Expected behavior

it was showing before the top skills of player but now it dont

### Actual behavior

i use mysql and this happened randomly and dont know how this happens even

### How to reproduce

it happend randomly

### Additional information

[08:29:44] [Server thread/WARN]: [AuraSkills] Error updating leaderboards: Cannot invoke "java.util.Map.keySet()" because the return value of "dev.aurelium.auraskills.common.user.UserState.skillLevels()" is null
[08:29:44] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because the return value of "dev.aurelium.auraskills.common.user.UserState.skillLevels()" is null
[08:29:44] [Server thread/WARN]: 	at AuraSkills-2.2.3.jar//dev.aurelium.auraskills.common.leaderboard.LeaderboardManager.addOfflinePlayers(LeaderboardManager.java:191)
[08:29:44] [Server thread/WARN]: 	at AuraSkills-2.2.3.jar//dev.aurelium.auraskills.common.leaderboard.LeaderboardManager.updateLeaderboardsSync(LeaderboardManager.java:55)
[08:29:44] [Server thread/WARN]: 	at AuraSkills-2.2.3.jar//dev.aurelium.auraskills.common.leaderboard.LeaderboardManager.updateLeaderboards(LeaderboardManager.java:38)
[08:29:44] [Server thread/WARN]: 	at AuraSkills-2.2.3.jar//dev.aurelium.auraskills.bukkit.AuraSkills.lambda$onEnable$0(AuraSkills.java:259)
[08:29:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
[08:29:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474)
[08:29:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1228)
[08:29:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[08:29:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
Did you manually modify the database at all? I'll have to do my own testing later

**Comment by Archy-X** [comment]
I wasn't able to reproduce it, but I made a change that might fix it. Can you try the latest dev build? https://aurelium.dev/auraskills/download?channel=dev
