### ISSUE TITLE
Compatibility Issue Between MMOItems and AuraSkills

### ISSUE THREAD

**Issue by Faeest** [Archy-X/AuraSkills#327]
### Server software and version

Paper 1.21.1

### Expected behavior

The RPG plugin compatibility should initialize without errors, allowing the MMOItems plugin to function correctly.

### Actual behavior

`[15:33:45] [Server thread/ERROR]: [MMOItems] Could not initialize RPG plugin compatibility with AuraSkills:
[15:33:45] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[15:33:45] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
[15:33:45] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)[15:33:45] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[15:33:45] [Server thread/WARN]: 	at MMOItems-6.10-30.jar//net.Indyuce.mmoitems.comp.rpg.RPGHandler$PluginEnum.load(RPGHandler.java:54)
[15:33:45] [Server thread/WARN]: 	at MMOItems-6.10-30.jar//net.Indyuce.mmoitems.MMOItems.findRpgPlugins(MMOItems.java:339)
[15:33:45] [Server thread/WARN]: 	at MMOItems-6.10-30.jar//net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:166)
[15:33:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[15:33:45] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[15:33:45] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[15:33:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[15:33:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[15:33:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[15:33:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753)
[15:33:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515)
[15:33:45] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
[15:33:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
[15:33:45] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[15:33:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[15:33:45] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: AuraSkillsApi is not initialized
[15:33:45] [Server thread/WARN]: 	at AuraSkills-2.2.0.jar//dev.aurelium.auraskills.api.AuraSkillsProvider.getInstance(AuraSkillsProvider.java:17)
[15:33:45] [Server thread/WARN]: 	at AuraSkills-2.2.0.jar//dev.aurelium.auraskills.api.AuraSkillsApi.get(AuraSkillsApi.java:122)
[15:33:45] [Server thread/WARN]: 	at MMOItems-6.10-30.jar//net.Indyuce.mmoitems.comp.rpg.AuraSkillsHook.<init>(AuraSkillsHook.java:43)
[15:33:45] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[15:33:45] [Server thread/WARN]: 	... 17 more`

### How to reproduce

Plugins : 
- AuraSkills 2.4.0
- MythicLib 1.6.1
- MythicMobs 5.8.0
- MMOItems 6.10 (DEV BUILD #_30)
- oraxen 1.182.0

### Additional information

I'm encountering an error related to the RPG plugin compatibility between **MMOItems** and **AuraSkills**. I have tested the latest development builds of **MMOItems**, as suggested [here](https://phoenixdevt.fr/devbuilds), but the issue persists. Therefore, I suspect the problem may lie on the **AuraSkills** side.

I have ensured that all plugins are up to date and compatible with **Paper 1.21.1**. It would be helpful to receive guidance on how to troubleshoot this issue further or possible fixes.

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by ErikSzabo** [comment]
You have a dependency circle...
AuraSkills -> Oraxen
Oraxen -> MMOItems
MMOItems -> AuraSkills

But modern plugin loading strategy on paper would tell you that anyways. There is a reason why that exists, you shouldn't disable it!
Try removing Oraxen or edit AuraSkills plugin.yml inside the jar file and remove Oraxen from soft dependencies

**Comment by Faeest** [comment]
It is! 😁 (I just wasted like a day sitting here tryna figuring this out 😭🙏)
