### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AuraSkills v2.2.5

### ISSUE THREAD

**Issue by servicomcr** [Archy-X/AuraSkills#331]
### Server software and version

This server is running Paper version 1.21.1-130-ver/1.21.1@4d2672e (2024-10-30T18:33:50Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Expected behavior

/na

### Actual behavior

java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.bukkit.level.BukkitLevelManager.playLevelUpSound(BukkitLevelManager.java:106) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.levelUpSkill(LevelManager.java:192) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.checkLevelUp(LevelManager.java:163) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.addXpRaw(LevelManager.java:70) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.bukkit.level.BukkitLevelManager.addDamageXp(BukkitLevelManager.java:98) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.bukkit.source.DamageLeveler.onDamage(DamageLeveler.java:96) ~[AuraSkills-2.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1101.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-130-4d2672e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:271) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:236) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:215) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1804) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

n/a

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
Looks like the 1.21.3 spigot-api made breaking changes to Sound, I reverted the upgrade so see if the latest dev build fixes the issue: https://aurelium.dev/auraskills/download?channel=dev
