### ISSUE TITLE
[AuraSkills] Task #564 for AuraSkills v2.2.5 generated an exception

### ISSUE THREAD

**Issue by servicomcr** [Archy-X/AuraSkills#332]
### Server software and version

This server is running Paper version 1.21.1-130-ver/1.21.1@4d2672e (2024-10-30T18:33:50Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Expected behavior

/na

### Actual behavior

[AuraSkills] Task #564 for AuraSkills v2.2.5 generated an exception
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.bukkit.level.BukkitLevelManager.playLevelUpSound(BukkitLevelManager.java:106) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.levelUpSkill(LevelManager.java:192) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.checkLevelUp(LevelManager.java:163) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.addXpRaw(LevelManager.java:70) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.common.level.LevelManager.addXp(LevelManager.java:61) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.bukkit.source.StatisticLeveler.handlePlayer(StatisticLeveler.java:68) ~[AuraSkills-2.2.5.jar:?]
        at AuraSkills-2.2.5.jar/dev.aurelium.auraskills.bukkit.source.StatisticLeveler$1.run(StatisticLeveler.java:35) ~[AuraSkills-2.2.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-130-4d2672e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

/na

### Additional information

/na

### Agreements

- [X] I am running the latest version of AuraSkills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/auraskills/incompatibilities)
- [X] My version of Minecraft is supported by AuraSkills

**Comment by Archy-X** [comment]
Closing because this is the same thing as #331
