### ISSUE TITLE
Error enabling Metrics!

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [Archy-X/AuraSkills#76]
### Server software and version

Papaer 1.18.1-132

### Expected behavior

[NBTAPI] Error enabling Metrics!" is displayed and the language setting is not reflected.

### Actual behavior

Error Description:
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[paper-1.18.1.jar:git-Paper-132]
        at com.archyx.aureliumskills.nbtapi.utils.ApiMetricsLite.<init>(ApiMetricsLite.java:144) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.utils.MinecraftVersion.init(MinecraftVersion.java:117) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.utils.MinecraftVersion.getVersion(MinecraftVersion.java:110) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.utils.MinecraftVersion.isAtLeastVersion(MinecraftVersion.java:75) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:69) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.utils.nmsmappings.ClassWrapper.<init>(ClassWrapper.java:55) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.utils.nmsmappings.ClassWrapper.<clinit>(ClassWrapper.java:17) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:35) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.nbtapi.NBTFile.<init>(NBTFile.java:36) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.region.RegionManager.loadRegion(RegionManager.java:114) ~[AureliumSkills-Beta1.2.7.jar:?]
        at com.archyx.aureliumskills.region.RegionListener$1.run(RegionListener.java:36) ~[AureliumSkills-Beta1.2.7.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-132]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-132]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

I really don't know, because it suddenly happened today. There was no change in the configuration from yesterday, I simply rebooted and it stopped working forever.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
Are you still experiencing this issue? If so, can you try updating to the latest paper?

**Comment by KonohanaSakuya2680** [comment]
> Are you still experiencing this issue? If so, can you try updating to the latest paper?

Sorry for the late reply.
As it turns out, the problem still exists after updating to Beta1.2.8.
I don't know if this will help, but I've updated the "AureliumSkills, AutoSaveWorld*, BetterPortals, ChestShop, CoreProtect, Corpses, CustomCrafting, ExecutableItems, FancyArmors*, floodgate, Geyser-Spigot, GeyserSkinManager, LightAPI, LuckPerms, LunaChat*, LWC, ProtocolLib, QualityArmory, SCore, SkinsRestorer, Vault, ViaBackwards, ViaVersion, WolfyUtilities, WorldEdit, WorldGuard" are currently installed.

**Comment by Archy-X** [comment]
Closing for inactivity. Reopen if you are still experiencing this issue.
